package modelo.entidades;
// Generated 24 feb. 2021 15:33:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private int idAutor;
	private String nombre;
	private String apellidos;
	private Set libros = new HashSet(0);

	public Autor() {
	}

	public Autor(int idAutor, String nombre, String apellidos) {
		this.idAutor = idAutor;
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public Autor(int idAutor, String nombre, String apellidos, Set libros) {
		this.idAutor = idAutor;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.libros = libros;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set getLibros() {
		return this.libros;
	}

	public void setLibros(Set libros) {
		this.libros = libros;
	}

}
