package modelo.entidades;
// Generated 24 feb. 2021 15:33:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ejemplar generated by hbm2java
 */
public class Ejemplar implements java.io.Serializable {

	private int idEjemplar;
	private Libro libro;
	private int numEjemplar;
	private String estado;
	@Override
	public String toString() {
		return "Ejemplar [idEjemplar=" + idEjemplar + ", libro=" + libro + ", numEjemplar=" + numEjemplar + ", estado="
				+ estado + ", prestamos=" + prestamos + "]";
	}

	private Set prestamos = new HashSet(0);

	public Ejemplar() {
	}

	public Ejemplar(int idEjemplar, Libro libro, int numEjemplar) {
		this.idEjemplar = idEjemplar;
		this.libro = libro;
		this.numEjemplar = numEjemplar;
	}

	public Ejemplar(int idEjemplar, Libro libro, int numEjemplar, String estado, Set prestamos) {
		this.idEjemplar = idEjemplar;
		this.libro = libro;
		this.numEjemplar = numEjemplar;
		this.estado = estado;
		this.prestamos = prestamos;
	}

	public int getIdEjemplar() {
		return this.idEjemplar;
	}

	public void setIdEjemplar(int idEjemplar) {
		this.idEjemplar = idEjemplar;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public int getNumEjemplar() {
		return this.numEjemplar;
	}

	public void setNumEjemplar(int numEjemplar) {
		this.numEjemplar = numEjemplar;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set prestamos) {
		this.prestamos = prestamos;
	}

}
